package com.jmg.consulmedico.view.usuario;

import Atxy2k.CustomTextField.RestrictedTextField;
import com.jmg.consulmedico.model.Usuario;

import javax.swing.*;


public class VModificarUsuario extends javax.swing.JFrame {

    private Usuario usuariomodificar;
    public VModificarUsuario(Usuario usuariomodificar) {
        initComponents();
        this.usuariomodificar=usuariomodificar;
        
        this.txtUsuario.setText(this.usuariomodificar.getNombre());
        this.txtUsuario.setEditable(false);
         RestrictedTextField restricted1 = new RestrictedTextField(this.txtUsuario);
        restricted1.setLimit(30);
         RestrictedTextField restricted2 = new RestrictedTextField(this.txtContraseña1);
        restricted2.setLimit(15);
            RestrictedTextField restricted3 = new RestrictedTextField(this.txtContraseña);
        restricted3.setLimit(15);
        this.setLocationRelativeTo(null);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jButton1 = new javax.swing.JButton();
        txtUsuario = new org.edisoncor.gui.textField.TextField();
        txtContraseña1 = new org.edisoncor.gui.passwordField.PasswordField();
        txtContraseña = new org.edisoncor.gui.passwordField.PasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N
        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Cambiar Contraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        txtUsuario.setEditable(false);
        panelImage1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 129, -1));
        panelImage1.add(txtContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, -1));
        panelImage1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña:");
        panelImage1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Nombre de Usuario:");
        panelImage1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Confirmar:");
        panelImage1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              if(this.validardatos())
              {
                  usuariomodificar.modificarUsuario(this.txtContraseña1.getText());
                  this.hide();
              }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.passwordField.PasswordField txtContraseña;
    private org.edisoncor.gui.passwordField.PasswordField txtContraseña1;
    private org.edisoncor.gui.textField.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private boolean validardatos() {
        if(this.txtContraseña.getText().equals(""))
        {
            JOptionPane.showMessageDialog(panelImage1, "No ha ingresado la contraseña nueva.");
            return false;
        }
         if(this.txtContraseña1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(panelImage1, "No ha ingresado la confirmación de la contraseña nueva.");
            return false;
        }
          if(!this.txtContraseña.getText().equals(this.txtContraseña.getText()))
        {
            JOptionPane.showMessageDialog(panelImage1, "Las contraseñas no coinciden.");
            return false;
        }
          return true;
    }
}
