/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.consulmedico.VISTA.PROCESARVISITA;

import com.jmg.consulmedico.BD.ConexionDB;
import com.jmg.consulmedico.MODELO.Turno;
import com.jmg.consulmedico.MODELO.Paciente;
import com.jmg.consulmedico.MODELO.Visita;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class VProcesarVisita extends javax.swing.JFrame {

    private Paciente paciente;
     private List<Turno> turnosdepaciente= new ArrayList<>();
   
     
     private boolean controlfecha;
     private boolean controlhora;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    public VProcesarVisita(Paciente paciente) {
        initComponents();
        this.paciente=paciente;
        
        Turno.buscarTurnosdePaciente(turnosdepaciente,paciente.getCodigopaciente());
        
       
        
            this.txtDni.setText(this.paciente.getDni());
        this.txtNombre.setText(this.paciente.getNombre());
        this.txtApellido.setText(this.paciente.getApellido());
        this.cboEspecialista.removeAllItems();
        this.cboEspecialista.addItem("  ");
        
        controlfecha=false;
        
        
        for(int i=0;i<this.turnosdepaciente.size();i++)
        {
            if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("Visita"))
            {
              this.cboEspecialista.addItem(((Visita)this.turnosdepaciente.get(i)).getMedico().getEspecialidad().getNombreEsp());
            }
        }
        
        
         if(this.cboEspecialista.getItemCount()==1)
        {
            JOptionPane.showMessageDialog(panelImage1, "Este Paciente no tiene visitas programadas.");
            this.hide();
            return;
        }
        controlfecha=true;
        
        this.setLocationRelativeTo(null);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        txtDni = new org.edisoncor.gui.textField.TextField();
        txtNombre = new org.edisoncor.gui.textField.TextField();
        txtApellido = new org.edisoncor.gui.textField.TextField();
        cboEspecialista = new javax.swing.JComboBox();
        cboFecha = new javax.swing.JComboBox();
        cboHora = new javax.swing.JComboBox();
        cmdProcesarTurnoVisita = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N
        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 416, -1));

        txtDni.setEditable(false);
        panelImage1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 73, 114, -1));

        txtNombre.setEditable(false);
        panelImage1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 104, 269, -1));

        txtApellido.setEditable(false);
        panelImage1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 135, 269, -1));

        cboEspecialista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEspecialistaItemStateChanged(evt);
            }
        });
        panelImage1.add(cboEspecialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 173, 180, -1));

        cboFecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboFechaItemStateChanged(evt);
            }
        });
        panelImage1.add(cboFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 203, 180, -1));

        panelImage1.add(cboHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 233, 180, -1));

        cmdProcesarTurnoVisita.setText("Atender Visita");
        cmdProcesarTurnoVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProcesarTurnoVisitaActionPerformed(evt);
            }
        });
        panelImage1.add(cmdProcesarTurnoVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 271, 180, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("DNI");
        panelImage1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Hora Turno");
        panelImage1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("Nombre Paciente");
        panelImage1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText("Apellido paciente");
        panelImage1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setText("Especialista");
        panelImage1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("Fecha Turno");
        panelImage1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboEspecialistaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEspecialistaItemStateChanged
      if(this.controlfecha)
      {
         
          this.controlhora=false;
           this.cboFecha.removeAllItems();
           this.cboFecha.addItem("");
        for(int i=0;i<this.turnosdepaciente.size();i++)
        {
            if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("Visita"))
            {
              if(this.cboEspecialista.getSelectedItem().equals(((Visita)this.turnosdepaciente.get(i)).getMedico().getEspecialidad().getNombreEsp()))
              {
                  this.cboFecha.addItem(((Visita)this.turnosdepaciente.get(i)).getFechaturno());
              }
            }
        }
        this.controlhora=true;
      }
      this.repaint();
    }//GEN-LAST:event_cboEspecialistaItemStateChanged

    private void cboFechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboFechaItemStateChanged
       
        if(this.controlhora)
      {
         this.cboHora.removeAllItems();
         this.cboHora.addItem("");
        for(int i=0;i<this.turnosdepaciente.size();i++)
        {
            if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("Visita"))
            {
              if(this.cboEspecialista.getSelectedItem().equals(((Visita)this.turnosdepaciente.get(i)).getMedico().getEspecialidad().getNombreEsp()))
              {
                  if(this.cboFecha.getSelectedItem().equals(((Visita)this.turnosdepaciente.get(i)).getFechaturno()))
                  {
                      this.cboHora.addItem(((Visita)this.turnosdepaciente.get(i)).getHorarioturno());
                  }
              }
            }
        }
       
      }
      this.repaint();
    }//GEN-LAST:event_cboFechaItemStateChanged

    private void cmdProcesarTurnoVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProcesarTurnoVisitaActionPerformed
        if(this.validardatos())
        {
        for(int i=0;i<this.turnosdepaciente.size();i++)
        {
            if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("Visita"))
            {
              if(this.cboEspecialista.getSelectedItem().equals(((Visita)this.turnosdepaciente.get(i)).getMedico().getEspecialidad().getNombreEsp()))
              {
                  if(this.cboFecha.getSelectedItem().equals(((Visita)this.turnosdepaciente.get(i)).getFechaturno()))
                  {
                     ((Visita)this.turnosdepaciente.get(i)).procesarTurnoVisita(new ConexionDB());
                      JOptionPane.showMessageDialog(null, "El turno del Paciente ha sido atendido. El médico correspondiente lo atenderá.");
              
                  }
              }
            }
        } }
         this.hide();
    }//GEN-LAST:event_cmdProcesarTurnoVisitaActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboEspecialista;
    private javax.swing.JComboBox cboFecha;
    private javax.swing.JComboBox cboHora;
    private javax.swing.JButton cmdProcesarTurnoVisita;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.textField.TextField txtApellido;
    private org.edisoncor.gui.textField.TextField txtDni;
    private org.edisoncor.gui.textField.TextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private boolean validardatos() {
        if(this.cboEspecialista.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "Debe seleccionar el médico para elegir la fecha y hora del turno que desea atender.");
            return false;
        }
        if(this.cboFecha.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "Debe seleccionar la fecha y hora del turno.");
            return false;
        }
        if(this.cboHora.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "Debe seleccionar la hora del turno.");
            return false;
        }
        return true;
    }
}
