/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.consulmedico.VISTA.SOLICITARTURNO;

import com.jmg.consulmedico.MODELO.Turno;
import com.jmg.consulmedico.MODELO.Visita;

/**
 *
 * @author Alumno
 */
public class VMostrarTurnoVisitaMedico extends javax.swing.JFrame {

    private Turno turnomedico;
    public VMostrarTurnoVisitaMedico(Turno turnomedico) {
        initComponents();
        this.turnomedico=turnomedico;
        this.txtCodigoTurno.setText(this.turnomedico.getCodigoturno()+"");
        this.txtFechaTurno.setText(this.turnomedico.getFechaturno()+"");
        this.txtHoraTurno.setText(this.turnomedico.getHorarioturno()+"");
        this.txtApellido.setText(this.turnomedico.getPaciente().getApellido());
        this.txtNombre.setText(this.turnomedico.getPaciente().getNombre());
       
        
        this.txtMatricula.setText(((Visita)this.turnomedico).getMedico().getNumMatricula());
        this.txtApellidoMedico.setText(((Visita)this.turnomedico).getMedico().getApellidoMed());
        this.txtNombreMedico.setText(((Visita)this.turnomedico).getMedico().getNombreMed());
        this.txtEspecialidadMedico.setText(((Visita)this.turnomedico).getMedico().getEspecialidad().getNombreEsp());
        
        
         
         
        
        
        
        
        
        
         this.setLocationRelativeTo(null);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        lblMadera = new javax.swing.JLabel();
        lblMadera1 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        txtCodigoTurno = new org.edisoncor.gui.textField.TextField();
        txtFechaTurno = new org.edisoncor.gui.textField.TextField();
        txtHoraTurno = new org.edisoncor.gui.textField.TextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        txtApellido = new org.edisoncor.gui.textField.TextField();
        txtNombre = new org.edisoncor.gui.textField.TextField();
        label6 = new java.awt.Label();
        txtMatricula = new org.edisoncor.gui.textField.TextField();
        label7 = new java.awt.Label();
        txtApellidoMedico = new org.edisoncor.gui.textField.TextField();
        txtNombreMedico = new org.edisoncor.gui.textField.TextField();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        txtEspecialidadMedico = new org.edisoncor.gui.textField.TextField();
        cmdAceptar = new javax.swing.JButton();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N
        panelImage2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMadera.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMadera.setText("Código de Turno");
        panelImage2.add(lblMadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 109, 24));

        lblMadera1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMadera1.setText("Datos de Paciente");
        panelImage2.add(lblMadera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 171, 24));

        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label2.setText("Apellido");
        panelImage2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 113, -1));

        txtCodigoTurno.setEditable(false);
        panelImage2.add(txtCodigoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 58, -1));

        txtFechaTurno.setEditable(false);
        panelImage2.add(txtFechaTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 100, -1));

        txtHoraTurno.setEditable(false);
        panelImage2.add(txtHoraTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 71, -1));

        label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label3.setText("Fecha de Turno");
        panelImage2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        label4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label4.setText("Hora de Turno");
        panelImage2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        label5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label5.setText("Nombre");
        panelImage2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 113, -1));

        txtApellido.setEditable(false);
        panelImage2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 258, -1));

        txtNombre.setEditable(false);
        panelImage2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 258, -1));

        label6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label6.setText("N° de Matrícula");
        panelImage2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 113, -1));

        txtMatricula.setEditable(false);
        panelImage2.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 160, -1));

        label7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label7.setText("Apellido Médico");
        panelImage2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 113, -1));

        txtApellidoMedico.setEditable(false);
        panelImage2.add(txtApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, -1));

        txtNombreMedico.setEditable(false);
        panelImage2.add(txtNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 160, -1));

        label8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label8.setText("Nombre Médico");
        panelImage2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 113, -1));

        label9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label9.setText("Especialidad");
        panelImage2.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 113, -1));

        txtEspecialidadMedico.setEditable(false);
        panelImage2.add(txtEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 160, -1));

        cmdAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Aceptar.png"))); // NOI18N
        cmdAceptar.setBorderPainted(false);
        cmdAceptar.setContentAreaFilled(false);
        cmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAceptarActionPerformed(evt);
            }
        });
        panelImage2.add(cmdAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MostrarTurno.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelImage2.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAceptarActionPerformed
      this.hide();
    }//GEN-LAST:event_cmdAceptarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAceptar;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JLabel lblMadera;
    private javax.swing.JLabel lblMadera1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.textField.TextField txtApellido;
    private org.edisoncor.gui.textField.TextField txtApellidoMedico;
    private org.edisoncor.gui.textField.TextField txtCodigoTurno;
    private org.edisoncor.gui.textField.TextField txtEspecialidadMedico;
    private org.edisoncor.gui.textField.TextField txtFechaTurno;
    private org.edisoncor.gui.textField.TextField txtHoraTurno;
    private org.edisoncor.gui.textField.TextField txtMatricula;
    private org.edisoncor.gui.textField.TextField txtNombre;
    private org.edisoncor.gui.textField.TextField txtNombreMedico;
    // End of variables declaration//GEN-END:variables
}
