/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.consulmedico.view.medicocabecera;

import com.jmg.consulmedico.config.ConexionDB;
import com.jmg.consulmedico.model.Especialidad;
import com.jmg.consulmedico.model.Medico;
import com.jmg.consulmedico.model.PacienteMedicoCabecera;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author Alumno
 */
public class VAutorizarVisitaEspecialista extends javax.swing.JFrame {
  

    
    public VAutorizarVisitaEspecialista(int codigomedico) {
        initComponents();
         List<String> nombrepacientes = Medico.retornarPacientesdeMedico(new ConexionDB(),codigomedico);
         for(int i=0;i<nombrepacientes.size();i++)
         {
             
             this.cboPacientes.addItem(nombrepacientes.get(i));
         }
         List<Especialidad> especialidades = Especialidad.retornarEspecialidad(new ConexionDB());
         for(int i=0;i<especialidades.size();i++)
         {
             if(!especialidades.get(i).equals("Médico"))
             {
                  this.cboEspecialidad.addItem(especialidades.get(i).getNombreEsp());
             }
         }
        this.repaint();
        
          this.setLocationRelativeTo(null);
        this.show();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        cboPacientes = new javax.swing.JComboBox();
        cboEspecialidad = new javax.swing.JComboBox();
        cmdAutorizarEstudio = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N

        cboPacientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir Paciente" }));

        cboEspecialidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir Especialista" }));

        cmdAutorizarEstudio.setText("Autorizar Visita");
        cmdAutorizarEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutorizarEstudioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Paciente");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Especialidad");

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboPacientes, 0, 193, Short.MAX_VALUE)))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(cmdAutorizarEstudio)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(cmdAutorizarEstudio)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAutorizarEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutorizarEstudioActionPerformed
        if(this.validarDatos())
        {
            PacienteMedicoCabecera.autorizarVisita(new ConexionDB(),(String)this.cboPacientes.getSelectedItem(),(String)this.cboEspecialidad.getSelectedItem());
        this.hide();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debe Selecionar el paciente y el estudio primero. Verifique haberlo hecho.");
        }
    }//GEN-LAST:event_cmdAutorizarEstudioActionPerformed

    /**
     * @param args the command line arguments
     */
    private boolean validarDatos() {
        if(this.cboPacientes.getSelectedIndex()==-1)
        {
            return false;
        }
        if(this.cboEspecialidad.getSelectedIndex()==-1)
        {
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboEspecialidad;
    private javax.swing.JComboBox cboPacientes;
    private javax.swing.JButton cmdAutorizarEstudio;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
