/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.consulmedico.view.procesarestudio;

import com.jmg.consulmedico.model.Paciente;
import com.jmg.consulmedico.model.Turno;
import com.jmg.consulmedico.model.TurnoEstudio;

import javax.swing.*;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Alumno
 */
public class VProcesarEstudio extends javax.swing.JFrame {

    private Paciente paciente;
     private List<Turno> turnosdepaciente= new ArrayList<>();
   
     
     private boolean controlfecha;
     private boolean controlhora;
    
    public VProcesarEstudio(Paciente paciente) {
        initComponents();
        this.paciente=paciente;
        
        Turno.buscarTurnosdePaciente(turnosdepaciente,paciente.getCodigopaciente());
        
       
        
            this.txtDni.setText(this.paciente.getDni());
        this.txtNombre.setText(this.paciente.getNombre());
        this.txtApellido.setText(this.paciente.getApellido());
        this.cboEspecialista.removeAllItems();
        this.cboEspecialista.addItem("  ");
        
        controlfecha=false;
        
        
        for(int i=0;i<this.turnosdepaciente.size();i++)
        {
            if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("TurnoEstudio"))
            {
              this.cboEspecialista.addItem(((TurnoEstudio)this.turnosdepaciente.get(i)).getEstudio().getEstudio());
            }
        }
        
        
         if(this.cboEspecialista.getItemCount()==1)
        {
            JOptionPane.showMessageDialog(panelImage1, "Este Paciente no tiene estudios programadas.");
            this.hide();
            return;
        }
        controlfecha=true;
        
        this.setLocationRelativeTo(null);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        txtDni = new org.edisoncor.gui.textField.TextField();
        txtNombre = new org.edisoncor.gui.textField.TextField();
        txtApellido = new org.edisoncor.gui.textField.TextField();
        cboEspecialista = new javax.swing.JComboBox();
        cboFecha = new javax.swing.JComboBox();
        cboHora = new javax.swing.JComboBox();
        cmdProcesarTurnoVisita = new javax.swing.JButton();
        txtFechaRetiro = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N
        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 416, -1));

        txtDni.setEditable(false);
        panelImage1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 73, 114, -1));

        txtNombre.setEditable(false);
        panelImage1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 104, 269, -1));

        txtApellido.setEditable(false);
        panelImage1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 135, 269, -1));

        cboEspecialista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEspecialistaItemStateChanged(evt);
            }
        });
        panelImage1.add(cboEspecialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 173, 180, -1));

        cboFecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboFechaItemStateChanged(evt);
            }
        });
        panelImage1.add(cboFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 203, 180, -1));

        panelImage1.add(cboHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 233, 180, -1));

        cmdProcesarTurnoVisita.setText("Atender Turno Estudio");
        cmdProcesarTurnoVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProcesarTurnoVisitaActionPerformed(evt);
            }
        });
        panelImage1.add(cmdProcesarTurnoVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 180, -1));

        txtFechaRetiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        panelImage1.add(txtFechaRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 130, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("DNI");
        panelImage1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 10));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Nombre Paciente");
        panelImage1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, 110, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Fecha Retiro");
        panelImage1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Apellido Paciente");
        panelImage1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Estudio");
        panelImage1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Fecha Turno");
        panelImage1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Hora Turno");
        panelImage1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboEspecialistaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEspecialistaItemStateChanged
      if(this.controlfecha)
      {
         
          this.controlhora=false;
           this.cboFecha.removeAllItems();
           this.cboFecha.addItem("");
        for(int i=0;i<this.turnosdepaciente.size();i++)
        {
            if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("TurnoEstudio"))
            {
              if(this.cboEspecialista.getSelectedItem().equals(((TurnoEstudio)this.turnosdepaciente.get(i)).getEstudio().getEstudio()))
              {
                  this.cboFecha.addItem(((TurnoEstudio)this.turnosdepaciente.get(i)).getFechaturno());
              }
            }
        }
        this.controlhora=true;
      }
      this.repaint();
    }//GEN-LAST:event_cboEspecialistaItemStateChanged

    private void cboFechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboFechaItemStateChanged
       
        if(this.controlhora)
      {
         this.cboHora.removeAllItems();
         this.cboHora.addItem("");
        for(int i=0;i<this.turnosdepaciente.size();i++)
        {
            if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("TurnoEstudio"))
            {
              if(this.cboEspecialista.getSelectedItem().equals(((TurnoEstudio)this.turnosdepaciente.get(i)).getEstudio().getEstudio()))
              {
                  if(this.cboFecha.getSelectedItem().equals(((TurnoEstudio)this.turnosdepaciente.get(i)).getFechaturno()))
                  {
                      this.cboHora.addItem(((TurnoEstudio)this.turnosdepaciente.get(i)).getHorarioturno());
                  }
              }
            }
        }
       
      }
      this.repaint();
    }//GEN-LAST:event_cboFechaItemStateChanged

    private void cmdProcesarTurnoVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProcesarTurnoVisitaActionPerformed
        if(this.validardatos())
        {
        for(int i=0;i<this.turnosdepaciente.size();i++)
        {
            if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("TurnoEstudio"))
            {
              if(this.cboEspecialista.getSelectedItem().equals(((TurnoEstudio)this.turnosdepaciente.get(i)).getEstudio().getEstudio()))
              {
                  if(this.cboFecha.getSelectedItem().equals(((TurnoEstudio)this.turnosdepaciente.get(i)).getFechaturno()))
                  {
                      ((TurnoEstudio)this.turnosdepaciente.get(i)).setPaciente(paciente);
                     ((TurnoEstudio)this.turnosdepaciente.get(i)).procesarTurnoEstudio();
                      Date fecha1;
                        int dia = Integer.parseInt(""+ this.txtFechaRetiro.getText().charAt(0)+this.txtFechaRetiro.getText().charAt(1));
                        int mes=Integer.parseInt(""+ this.txtFechaRetiro.getText().charAt(3)+this.txtFechaRetiro.getText().charAt(4));
                        int anio =Integer.parseInt(""+ this.txtFechaRetiro.getText().charAt(6)+this.txtFechaRetiro.getText().charAt(7)+ this.txtFechaRetiro.getText().charAt(8)+this.txtFechaRetiro.getText().charAt(9));
                       anio=2014;
                        fecha1 = new Date(anio,mes,dia);
                         
                                   
                     
                     
                     
                     VTalonRetiroEstudio mostrartalon = new VTalonRetiroEstudio(((TurnoEstudio)this.turnosdepaciente.get(i)),fecha1,this.txtFechaRetiro.getText());
                     this.hide();
                  }
              }
            }
        } }
         this.hide();
    }//GEN-LAST:event_cmdProcesarTurnoVisitaActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboEspecialista;
    private javax.swing.JComboBox cboFecha;
    private javax.swing.JComboBox cboHora;
    private javax.swing.JButton cmdProcesarTurnoVisita;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.textField.TextField txtApellido;
    private org.edisoncor.gui.textField.TextField txtDni;
    private javax.swing.JFormattedTextField txtFechaRetiro;
    private org.edisoncor.gui.textField.TextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private boolean validardatos() {
        if(this.cboEspecialista.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "Debe seleccionar el médico para elegir la fecha y hora del turno que desea atender.");
            return false;
        }
        if(this.cboFecha.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "Debe seleccionar la fecha y hora del turno.");
            return false;
        }
        if(this.cboHora.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "Debe seleccionar la hora del turno.");
            return false;
        }
        if(this.txtFechaRetiro.getText().equals(""))
        {
            JOptionPane.showMessageDialog(panelImage1, "No ha ingresado la fecha de retiro");
            return false;
        }
        return true;
    }
}
