/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.consulmedico.VISTA;

import Atxy2k.CustomTextField.RestrictedTextField;
import com.jmg.consulmedico.MODELO.Paciente;
import com.jmg.consulmedico.VISTA.CANCELARTURNO.VCancelarTurno;
import com.jmg.consulmedico.VISTA.PROCESARESTUDIO.VProcesarEstudio;
import com.jmg.consulmedico.VISTA.PROCESARVISITA.VProcesarVisita;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class VBuscarPaciente extends javax.swing.JFrame {

    private String redireccionamiento ="";
    private Paciente paciente = null;
    
    public VBuscarPaciente(String redireccion) {
        initComponents();
        this.redireccionamiento=redireccion;
           this.setLocationRelativeTo(null);
        this.show();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        cboBusqueda = new javax.swing.JComboBox();
        lblBusqueda = new java.awt.Label();
        txtBusqueda = new org.edisoncor.gui.textField.TextField();
        cmdBuscarPaciente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N

        cboBusqueda.setBackground(new java.awt.Color(204, 204, 204));
        cboBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dni", "Código de Historial Clínico", "Nombre y Apellido" }));
        cboBusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBusquedaItemStateChanged(evt);
            }
        });

        lblBusqueda.setBackground(new java.awt.Color(226, 239, 250));
        lblBusqueda.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblBusqueda.setText("DNI");

        txtBusqueda.setBackground(new java.awt.Color(204, 204, 204));
        txtBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        txtBusqueda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        cmdBuscarPaciente.setBackground(new java.awt.Color(255, 255, 153));
        cmdBuscarPaciente.setText("Buscar Paciente");
        cmdBuscarPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdBuscarPaciente.setFocusPainted(false);
        cmdBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarPacienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Tipo de Busqueda");

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelImage1Layout.createSequentialGroup()
                                .addComponent(lblBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(cmdBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(cmdBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboBusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBusquedaItemStateChanged
       this.lblBusqueda.setText((String)this.cboBusqueda.getSelectedItem());
      
    }//GEN-LAST:event_cboBusquedaItemStateChanged

    private void cmdBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarPacienteActionPerformed
      if(this.validardatos())
      {
        switch((String)this.cboBusqueda.getSelectedItem())  
         {
             case "Dni":
                 this.paciente=Paciente.buscarPorDNI(this.txtBusqueda.getText());
                 break;
             case "Código de Historial Clínico":
                 this.paciente=Paciente.buscarPorCodigoHistoriaClinica(this.txtBusqueda.getText());
                  break;
             case "Nombre y Apellido":
                  this.paciente=Paciente.buscarPorNombreyApellido(this.txtBusqueda.getText()); 
                 
                 break;
         }
         
         if(this.paciente==null)
         {
             JOptionPane.showMessageDialog(panelImage1, "Este paciente no existe.");
         }
         else
         {
             switch(this.redireccionamiento)
             {
                 case "Cancelar Turno":
                     VCancelarTurno cancelarturno = new VCancelarTurno(this.paciente,false);
                     break;
                 case "Procesar Visita":
                     VProcesarVisita procesarvisita = new VProcesarVisita(this.paciente);
                     break;
                 case "Procesar Estudio":
                     VProcesarEstudio procesarestudio = new VProcesarEstudio(this.paciente);
                     
                     break;
                 case "Cambiar Turno":
                      VCambiarTurno cambiarturno = new VCambiarTurno(this.paciente);
                     break;
             }
             
             
             
             
             
             this.hide();
         }
      }
    }//GEN-LAST:event_cmdBuscarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboBusqueda;
    private javax.swing.JButton cmdBuscarPaciente;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label lblBusqueda;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.textField.TextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    private boolean validardatos() {
       if(this.cboBusqueda.getSelectedIndex()==-1)
        {
             JOptionPane.showMessageDialog(panelImage1, "No ha seleccionado el tipo de busqueda con el que desea encontrar al paciente.");
            return false;
        }
       if(this.txtBusqueda.getText().equals(""))
        {
             JOptionPane.showMessageDialog(panelImage1, "No ha ingresado el " + this.lblBusqueda.getText() + " del paciente.");
            return false;
        }
       return true;
    
    }
}
