/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.consulmedico.view;

import com.jmg.consulmedico.config.ConexionDB;
import com.jmg.consulmedico.model.Paciente;
import com.jmg.consulmedico.model.Turno;
import com.jmg.consulmedico.model.TurnoEstudio;
import com.jmg.consulmedico.model.Visita;

import javax.swing.*;
import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Alumno
 */
public class VCambiarTurno extends javax.swing.JFrame {

    private Paciente paciente;
    private List<Turno> turnosdepaciente= new ArrayList<>();
    private boolean control=true;
    public VCambiarTurno(Paciente paciente) {
        initComponents();
        this.paciente = paciente;
        Turno.buscarTurnosdePaciente(turnosdepaciente,paciente.getCodigopaciente());
        this.txtDni.setText(this.paciente.getDni());
        this.panelDetalle.setVisible(false);
         this.control=false;
          Turno.recuperarFechas(this.cboFechas);
    
         this.control=true;
        this.setLocationRelativeTo(null);
        this.show();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        label2 = new java.awt.Label();
        txtDni = new org.edisoncor.gui.textField.TextField();
        label1 = new java.awt.Label();
        cboTipoTurno = new javax.swing.JComboBox();
        label3 = new java.awt.Label();
        cboTurno = new javax.swing.JComboBox();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelDetalle = new org.edisoncor.gui.panel.PanelImage();
        lblEstudiooMedico = new java.awt.Label();
        txtEstudiooMedico = new org.edisoncor.gui.textField.TextField();
        lblEstudiooMedico1 = new java.awt.Label();
        txtFechaTurno = new org.edisoncor.gui.textField.TextField();
        lblEstudiooMedico2 = new java.awt.Label();
        txtHoraTurno = new org.edisoncor.gui.textField.TextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        cboFechas = new javax.swing.JComboBox();
        cboHorarios = new javax.swing.JComboBox();
        cmdCambiarTurno = new javax.swing.JButton();

        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N
        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("DNI");
        panelImage1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 88, 131, 24));

        txtDni.setEditable(false);
        txtDni.setBackground(new java.awt.Color(204, 204, 204));
        txtDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDni.setForeground(new java.awt.Color(255, 255, 255));
        txtDni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelImage1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 88, 145, 24));

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Tipo de Turno");
        panelImage1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 123, 131, -1));

        cboTipoTurno.setBackground(new java.awt.Color(204, 204, 204));
        cboTipoTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Realizar Estudio", "Visitar Médico" }));
        cboTipoTurno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoTurnoItemStateChanged(evt);
            }
        });
        panelImage1.add(cboTipoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 123, 185, 24));

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Turno");
        panelImage1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 157, 131, -1));

        cboTurno.setBackground(new java.awt.Color(204, 204, 204));
        cboTurno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTurnoItemStateChanged(evt);
            }
        });
        cboTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTurnoActionPerformed(evt);
            }
        });
        panelImage1.add(cboTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 157, 185, 24));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CambiarTurnoTitulo.png"))); // NOI18N
        panelImage2.setPreferredSize(new java.awt.Dimension(0, 58));

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 369, -1));

        panelDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N
        panelDetalle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEstudiooMedico.setBackground(new java.awt.Color(239, 249, 255));
        lblEstudiooMedico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblEstudiooMedico.setText("Estudio");
        panelDetalle.add(lblEstudiooMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 131, -1));

        txtEstudiooMedico.setEditable(false);
        txtEstudiooMedico.setBackground(new java.awt.Color(204, 204, 204));
        txtEstudiooMedico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEstudiooMedico.setForeground(new java.awt.Color(255, 255, 255));
        txtEstudiooMedico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDetalle.add(txtEstudiooMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 11, 178, 20));

        lblEstudiooMedico1.setBackground(new java.awt.Color(231, 242, 252));
        lblEstudiooMedico1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblEstudiooMedico1.setText("Fecha Turno");
        panelDetalle.add(lblEstudiooMedico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 41, 131, -1));

        txtFechaTurno.setEditable(false);
        txtFechaTurno.setBackground(new java.awt.Color(204, 204, 204));
        txtFechaTurno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFechaTurno.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaTurno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDetalle.add(txtFechaTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 41, 86, 20));

        lblEstudiooMedico2.setBackground(new java.awt.Color(231, 242, 252));
        lblEstudiooMedico2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblEstudiooMedico2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblEstudiooMedico2.setText("Hora Turno");
        panelDetalle.add(lblEstudiooMedico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 71, 131, -1));

        txtHoraTurno.setEditable(false);
        txtHoraTurno.setBackground(new java.awt.Color(204, 204, 204));
        txtHoraTurno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHoraTurno.setForeground(new java.awt.Color(255, 255, 255));
        txtHoraTurno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtHoraTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraTurnoActionPerformed(evt);
            }
        });
        panelDetalle.add(txtHoraTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 71, 86, 20));

        label4.setBackground(new java.awt.Color(225, 237, 250));
        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Horario");
        panelDetalle.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        label5.setBackground(new java.awt.Color(225, 237, 249));
        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Fecha");
        panelDetalle.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        cboFechas.setBackground(new java.awt.Color(204, 204, 204));
        cboFechas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboFechasItemStateChanged(evt);
            }
        });
        panelDetalle.add(cboFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, -1));

        cboHorarios.setBackground(new java.awt.Color(204, 204, 204));
        cboHorarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHorariosItemStateChanged(evt);
            }
        });
        panelDetalle.add(cboHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, -1));

        panelImage1.add(panelDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, -1, 170));

        cmdCambiarTurno.setBackground(new java.awt.Color(204, 255, 255));
        cmdCambiarTurno.setText("Cambiar Turno");
        cmdCambiarTurno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCambiarTurno.setBorderPainted(false);
        cmdCambiarTurno.setFocusPainted(false);
        cmdCambiarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarTurnoActionPerformed(evt);
            }
        });
        panelImage1.add(cmdCambiarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 168, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipoTurnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoTurnoItemStateChanged
         this.cboTurno.removeAllItems(); 
        
         
         this.cboTurno.addItem("");
        if(((String)this.cboTipoTurno.getSelectedItem()).equals("Realizar Estudio"))
          {
               for(int i=0;i<this.turnosdepaciente.size();i++)
               {
                   if(this.turnosdepaciente.get(i).getClass().getSimpleName().equals("TurnoEstudio"))
                   {
                       this.cboTurno.addItem(this.turnosdepaciente.get(i).getFechaturno()+ " " + this.turnosdepaciente.get(i).getHorarioturno());
                       this.turnosdepaciente.get(i).setPaciente(paciente);
                   }
               }
              
          }
        else
        {
            for(int i=0;i<this.turnosdepaciente.size();i++)
               {
                   if(!this.turnosdepaciente.get(i).getClass().getSimpleName().equals("TurnoEstudio"))
                   {
                       this.cboTurno.addItem(this.turnosdepaciente.get(i).getFechaturno()+ " " + this.turnosdepaciente.get(i).getHorarioturno());
                      this.turnosdepaciente.get(i).setPaciente(paciente);
                  
                   }
               }
        }
         this.panelDetalle.setVisible(false);
         
         this.txtEstudiooMedico.setText("");
         this.txtFechaTurno.setText("");
         this.txtHoraTurno.setText("");
        this.repaint();
    }//GEN-LAST:event_cboTipoTurnoItemStateChanged

    private void cboTurnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTurnoItemStateChanged
        this.panelDetalle.setVisible(true);
        for(int i=0;i<this.turnosdepaciente.size();i++)
         {
                   if((this.turnosdepaciente.get(i).getFechaturno()+ " " + this.turnosdepaciente.get(i).getHorarioturno()).equals(this.cboTurno.getSelectedItem()))
                   {
                       if(!this.turnosdepaciente.get(i).getClass().getSimpleName().equals("TurnoEstudio"))
                        {
                           this.lblEstudiooMedico.setText("Medico");
                           this.txtEstudiooMedico.setText(((Visita)this.turnosdepaciente.get(i)).getMedico().getApellidoMed()+ " " +((Visita)this.turnosdepaciente.get(i)).getMedico().getNombreMed());
                           this.txtFechaTurno.setText(((Visita)this.turnosdepaciente.get(i)).getFechaturno()+"");
                           this.txtHoraTurno.setText(((Visita)this.turnosdepaciente.get(i)).getHorarioturno()+"");
                           
                         
                        }
                       else
                       {
                           this.lblEstudiooMedico.setText("Estudio");
                           this.txtEstudiooMedico.setText(((TurnoEstudio)this.turnosdepaciente.get(i)).getEstudio().getEstudio());
                           this.txtFechaTurno.setText(((TurnoEstudio)this.turnosdepaciente.get(i)).getFechaturno()+"");
                           this.txtHoraTurno.setText(((TurnoEstudio)this.turnosdepaciente.get(i)).getHorarioturno()+"");
                           
                       }
                   }
        }
        
        
       
         this.repaint();
    }//GEN-LAST:event_cboTurnoItemStateChanged

    private void txtHoraTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraTurnoActionPerformed

    private void cmdCambiarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarTurnoActionPerformed
      if(this.validardatos())
      {
        for(int i=0;i<this.turnosdepaciente.size();i++)
         {
                   if((this.turnosdepaciente.get(i).getFechaturno()+ " " + this.turnosdepaciente.get(i).getHorarioturno()).equals(this.cboTurno.getSelectedItem()))
                   {
                      this.turnosdepaciente.get(i).cancelarTurno();
                      this.turnosdepaciente.get(i).setFechaturno((Date)this.cboFechas.getSelectedItem());
                      this.turnosdepaciente.get(i).setHorarioturno((Time)this.cboHorarios.getSelectedItem());
         
                      this.turnosdepaciente.get(i).almacenarTurno(new ConexionDB());
                      JOptionPane.showMessageDialog(panelImage1, "El turno fue modificado exitosamente."); 
                   }
        }
         this.repaint();
         
       
             JOptionPane.showMessageDialog(panelImage1, "El turno fue cancelado existosamente");
       
       
    this.hide();
      }
      
    }//GEN-LAST:event_cmdCambiarTurnoActionPerformed

    private void cboTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTurnoActionPerformed

    private void cboFechasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboFechasItemStateChanged
        if(this.control==true)
        {
              for(int i=0;i<this.turnosdepaciente.size();i++)
              {
                        if((this.turnosdepaciente.get(i).getFechaturno()+ " " + this.turnosdepaciente.get(i).getHorarioturno()).equals(this.cboTurno.getSelectedItem()))
                        {
                             if(!this.turnosdepaciente.get(i).getClass().getSimpleName().equals("TurnoEstudio"))
                                {
                                    this.turnosdepaciente.get(i).setTipodeturno("Visitar Especialista");
                                     Visita.llenarHorariosDisponibles(this.cboHorarios,((Date)this.cboFechas.getSelectedItem()),((Visita)this.turnosdepaciente.get(i)).getMedico());
                                     this.repaint();
      

                                }
                               else
                               {
                                     this.turnosdepaciente.get(i).setTipodeturno("Realizar Estudio");
                                  
                                    TurnoEstudio.llenarHorariosDisponibles(this.cboHorarios,((Date)this.cboFechas.getSelectedItem()),((TurnoEstudio)this.turnosdepaciente.get(i)));
                                    this.repaint();
                               }
                            
                        }
              }
        }
    }//GEN-LAST:event_cboFechasItemStateChanged

    private void cboHorariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHorariosItemStateChanged

    }//GEN-LAST:event_cboHorariosItemStateChanged

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboFechas;
    private javax.swing.JComboBox cboHorarios;
    private javax.swing.JComboBox cboTipoTurno;
    private javax.swing.JComboBox cboTurno;
    private javax.swing.JButton cmdCambiarTurno;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label lblEstudiooMedico;
    private java.awt.Label lblEstudiooMedico1;
    private java.awt.Label lblEstudiooMedico2;
    private org.edisoncor.gui.panel.PanelImage panelDetalle;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.textField.TextField txtDni;
    private org.edisoncor.gui.textField.TextField txtEstudiooMedico;
    private org.edisoncor.gui.textField.TextField txtFechaTurno;
    private org.edisoncor.gui.textField.TextField txtHoraTurno;
    // End of variables declaration//GEN-END:variables

    private boolean validardatos() {
        if(this.cboTipoTurno.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "No seleccionó el tipo de turno que desea cambiar");
            return false;
        }
         if(this.cboTurno.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "No seleccionó el turno que desea cambiar");
            return false;
        }
         
          if(this.cboFechas.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "No seleccionó la fecha que desea cambiar el turno.");
            return false;
        }
         if(this.cboHorarios.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(panelImage1, "No seleccionó la hora que desea cambiar el turno.");
            return false;
        }
        
        
        
        
        
        return true;
    }

    
}
