package com.jmg.consulmedico.view;

import com.jmg.consulmedico.model.Usuario;
import com.jmg.consulmedico.view.medico.VAltaMedico;
import com.jmg.consulmedico.view.medicocabecera.VAltaObraSocial;
import com.jmg.consulmedico.view.turno.VSolicitarTurno;
import com.jmg.consulmedico.view.usuario.VAltaUsuarios;
import com.jmg.consulmedico.view.usuario.VModificarUsuario;

import javax.swing.*;


public class VMenuPrincipal extends javax.swing.JFrame {

    private Usuario usuario;
   
    
    public VMenuPrincipal(Usuario usuario) {
        initComponents();
        this.usuario=usuario;
          this.setLocationRelativeTo(null);
        this.show();
    }

    public JButton getCmdRegistrarMedico() {
        return cmdRegistrarMedico;
    }

    public JButton getCmdRegistrarUsuarios() {
        return cmdRegistrarUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        cmdCambiarTurnoEstudio = new javax.swing.JButton();
        cmdCancelarTurno = new javax.swing.JButton();
        cmdAtenderTurnoEstudio = new javax.swing.JButton();
        cmdRegistrarUsuarios = new javax.swing.JButton();
        cmdConfigurarUsuario = new javax.swing.JButton();
        cmdAltaObraSocial = new javax.swing.JButton();
        cmdProcesarTurnoVisita = new javax.swing.JButton();
        cmdRegistrarMedico = new javax.swing.JButton();
        cmdSolicitarTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelImage2.setBackground(new java.awt.Color(51, 153, 255));
        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Altapacientefondo.png"))); // NOI18N
        panelImage2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCambiarTurnoEstudio.setBackground(new java.awt.Color(153, 255, 102));
        cmdCambiarTurnoEstudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdCambiarTurnoEstudio.setForeground(new java.awt.Color(51, 51, 51));
        cmdCambiarTurnoEstudio.setText("Cambiar Turno");
        cmdCambiarTurnoEstudio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCambiarTurnoEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarTurnoEstudioActionPerformed(evt);
            }
        });
        panelImage2.add(cmdCambiarTurnoEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 161, 40));

        cmdCancelarTurno.setBackground(new java.awt.Color(153, 255, 102));
        cmdCancelarTurno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdCancelarTurno.setForeground(new java.awt.Color(51, 51, 51));
        cmdCancelarTurno.setText("Cancelar Turno");
        cmdCancelarTurno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCancelarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarTurnoActionPerformed(evt);
            }
        });
        panelImage2.add(cmdCancelarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 20, 161, 40));

        cmdAtenderTurnoEstudio.setBackground(new java.awt.Color(153, 255, 102));
        cmdAtenderTurnoEstudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdAtenderTurnoEstudio.setForeground(new java.awt.Color(51, 51, 51));
        cmdAtenderTurnoEstudio.setText("Atender Turno Estudio");
        cmdAtenderTurnoEstudio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdAtenderTurnoEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAtenderTurnoEstudioActionPerformed(evt);
            }
        });
        panelImage2.add(cmdAtenderTurnoEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 72, 161, 40));

        cmdRegistrarUsuarios.setBackground(new java.awt.Color(153, 255, 102));
        cmdRegistrarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdRegistrarUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        cmdRegistrarUsuarios.setText("Registrar Usuarios");
        cmdRegistrarUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarUsuariosActionPerformed(evt);
            }
        });
        panelImage2.add(cmdRegistrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 228, 161, 40));

        cmdConfigurarUsuario.setBackground(new java.awt.Color(153, 255, 102));
        cmdConfigurarUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdConfigurarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        cmdConfigurarUsuario.setText("Configurar Usuario");
        cmdConfigurarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdConfigurarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConfigurarUsuarioActionPerformed(evt);
            }
        });
        panelImage2.add(cmdConfigurarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 161, 40));

        cmdAltaObraSocial.setBackground(new java.awt.Color(153, 255, 102));
        cmdAltaObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdAltaObraSocial.setForeground(new java.awt.Color(51, 51, 51));
        cmdAltaObraSocial.setText("Alta Obra Social");
        cmdAltaObraSocial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdAltaObraSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAltaObraSocialActionPerformed(evt);
            }
        });
        panelImage2.add(cmdAltaObraSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 124, 161, 40));

        cmdProcesarTurnoVisita.setBackground(new java.awt.Color(153, 255, 102));
        cmdProcesarTurnoVisita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdProcesarTurnoVisita.setForeground(new java.awt.Color(51, 51, 51));
        cmdProcesarTurnoVisita.setText("Procesar Turno Visita");
        cmdProcesarTurnoVisita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdProcesarTurnoVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProcesarTurnoVisitaActionPerformed(evt);
            }
        });
        panelImage2.add(cmdProcesarTurnoVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, 161, 40));

        cmdRegistrarMedico.setBackground(new java.awt.Color(153, 255, 102));
        cmdRegistrarMedico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdRegistrarMedico.setForeground(new java.awt.Color(51, 51, 51));
        cmdRegistrarMedico.setText("Registrar Médico");
        cmdRegistrarMedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdRegistrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarMedicoActionPerformed(evt);
            }
        });
        panelImage2.add(cmdRegistrarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 175, 161, 40));

        cmdSolicitarTurno.setBackground(new java.awt.Color(153, 255, 102));
        cmdSolicitarTurno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdSolicitarTurno.setForeground(new java.awt.Color(51, 51, 51));
        cmdSolicitarTurno.setText("Solicitar Turno");
        cmdSolicitarTurno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdSolicitarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSolicitarTurnoActionPerformed(evt);
            }
        });
        panelImage2.add(cmdSolicitarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 161, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSolicitarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSolicitarTurnoActionPerformed
       VSolicitarTurno vsolicitarturno = new VSolicitarTurno();
       
    }//GEN-LAST:event_cmdSolicitarTurnoActionPerformed

    private void cmdCancelarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarTurnoActionPerformed
        VBuscarPaciente buscarpaciente = new VBuscarPaciente("Cancelar Turno");
        
    }//GEN-LAST:event_cmdCancelarTurnoActionPerformed

    private void cmdRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarUsuariosActionPerformed
        VAltaUsuarios valta = new VAltaUsuarios();
    }//GEN-LAST:event_cmdRegistrarUsuariosActionPerformed

    private void cmdConfigurarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConfigurarUsuarioActionPerformed
        VModificarUsuario modificar = new VModificarUsuario(this.usuario);
        
    }//GEN-LAST:event_cmdConfigurarUsuarioActionPerformed

    private void cmdAltaObraSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAltaObraSocialActionPerformed
      VAltaObraSocial vobrasocial = new VAltaObraSocial();
    }//GEN-LAST:event_cmdAltaObraSocialActionPerformed

    private void cmdProcesarTurnoVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProcesarTurnoVisitaActionPerformed
       VBuscarPaciente vprocesarvisita = new VBuscarPaciente("Procesar Visita");
       
    }//GEN-LAST:event_cmdProcesarTurnoVisitaActionPerformed

    private void cmdAtenderTurnoEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAtenderTurnoEstudioActionPerformed
          VBuscarPaciente vprocesarvisita = new VBuscarPaciente("Procesar Estudio");
    
    }//GEN-LAST:event_cmdAtenderTurnoEstudioActionPerformed

    private void cmdCambiarTurnoEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarTurnoEstudioActionPerformed
         VBuscarPaciente vprocesarvisita = new VBuscarPaciente("Cambiar Turno");
     
    }//GEN-LAST:event_cmdCambiarTurnoEstudioActionPerformed

    private void cmdRegistrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarMedicoActionPerformed
       VAltaMedico valtamedico = new VAltaMedico();
       
    }//GEN-LAST:event_cmdRegistrarMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAltaObraSocial;
    private javax.swing.JButton cmdAtenderTurnoEstudio;
    private javax.swing.JButton cmdCambiarTurnoEstudio;
    private javax.swing.JButton cmdCancelarTurno;
    private javax.swing.JButton cmdConfigurarUsuario;
    private javax.swing.JButton cmdProcesarTurnoVisita;
    private javax.swing.JButton cmdRegistrarMedico;
    private javax.swing.JButton cmdRegistrarUsuarios;
    private javax.swing.JButton cmdSolicitarTurno;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    // End of variables declaration//GEN-END:variables
}
